name: Release
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tags'
  push:
    branches:
       - "main"
    tags:
      - "v*"

jobs:
    release_CPU:
        runs-on: linux-ubuntu22.04
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASS }}
            - name: get latest tag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"
              id: get-latest-tag
            - name: Build and push
              uses: docker/build-push-action@v3
              env:
                TAG: ${{ steps.get-latest-tag.outputs.tag || github.event.inputs.tags || 'latest'}} 
              with:
                context: .
                file: ./docker/CPUDockerfile
                push: true
                tags: beclab/ioPaint-cpu:${{env.TAG}}
                platforms: linux/amd64
    release_GPU:
        runs-on: linux-ubuntu22.04
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASS }}
            - name: get latest tag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"
              id: get-latest-tag
            - name: Build and push
              uses: docker/build-push-action@v3
              env:
                TAG: ${{ steps.get-latest-tag.outputs.tag || github.event.inputs.tags || 'latest'}} 
              with:
                context: .
                file: ./docker/GPUDockerfile
                push: true
                tags: beclab/ioPaint-gpu:${{env.TAG}}
                platforms: linux/amd64
